version: '3'

networks: 
    laravel:

services:
    nginx:
        image: nginx:latest
        container_name: g_nginx
        ports:
            - "8088:80"
        volumes: 
            - ./src:/var/www/html 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/access.log:/var/log/nginx/access.log
            
        depends_on: 
            - php
            - mongo
            - npm
        networks: 
            - laravel
    
    mongo:
        container_name: gm_mongo
        image:  hiepdv/docker-test:mongodb-3.2.18
        ports:
            - 27029:27017
        networks: 
            - laravel

    php:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: g_php
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - laravel
    
    npm:
        image: node:latest
        container_name: g_npm 
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks: 
            - laravel